[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1_000
evm_version="cancun"

remappings = [
    "@ds-test/=lib/forge-std/lib/ds-test/src/",
    "@forge-std/=lib/forge-std/src/",
    "@src/=src/",
    "@test/=test/",
    "@script/=script/",

    # deps
    "@safe-contracts/=lib/safe-contracts/contracts/",
    "@solmate/=lib/solmate/src/",
    "@euler-price-oracle/=lib/euler-price-oracle/src/",
    "@solady/=lib/solady/src/",
    "@zodiac/=lib/zodiac/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@permit2/=lib/permit2/",

    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    #####
    ### @dev This import is so we can compile the euler price oracle contracts inside tests
    "ethereum-vault-connector/=lib/euler-price-oracle/lib/ethereum-vault-connector/src/",
    #### this is to compile the permit2 contracts
    "solmate/src/=lib/permit2/lib/solmate/src/",
    ##### compile zodiac contracts
    "@gnosis.pm/safe-contracts/contracts/=lib/safe-contracts/contracts/"
] 

fs_permissions = [{ access = "read", path = "./"}]


[profile.default.fuzz]
runs = 2048

[fmt]
line_length = 100